version: '3.3'
services:
  app1:
    build: .
    ports:
      - "8000:80"
    environment:
      - SERVER_NAME=App1
  app2:
    build: .
    ports:
      - "8001:80"
    environment:
      - SERVER_NAME=App2
